name: Node.js Unit CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        node-version: [16]
        dapr-version: [1.6.3, 1.7.4, 1.8.3, 1.9.2]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Install SkyWalking
        run: docker pull apache/skywalking-oap-server:9.2.0

      - name: Install Dapr CLI
        uses: dapr/setup-dapr@v1
        with:
          version: '1.9.1'

      - name: Initialize Dapr Runtime
        run: dapr init -s --runtime-version ${{ matrix.dapr-version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Project Dependencies
        run: npm install

      - name: Build TypeScript Project
        run: npm run build --if-present

      - name: Run Tests
        run: npm test
